name: "ci build"

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@1.8.2
        with:
          extensions: mbstring, intl, pdo, pdo_pgsql, bcmath, curl, xml, ctype, iconv, pgsql
          php-version: "${{ matrix.php-versions }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Validate composer.json and composer.lock"
        run: "composer validate"
      - name: "Install dependencies"
        run: "composer install --prefer-dist --no-progress --no-suggest"
      - name: "Code analyze"
        run: "composer analyze"
      - name: "CS Check"
        run: "composer cs-check"
      - name: "DB Fixture"
        run: "cp config/autoload/local.php.travis.dist config/autoload/local.php && docker exec -d postgres psql -h 127.0.0.1 -d postgres -U postgres -p 5432 -a -q -f data/postgresql.sql"
      - name: "Run test suite"
        run: "composer  test"
